services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data  # ruta_externa:ruta_interna (contenedor)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  # Database admin service
  adminer:
  container_name: adminer
  image: adminer
  restart: always
  depends_on: 
    - postgres_db
  ports:
   -9090:8080