services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data  # ruta_externa:ruta_interna (contenedor)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  # Database admin service
  adminer:
  container_name: adminer
  image: adminer
  restart: always
  depends_on: 
    - postgres_db
  ports:
   -9090:8080

  # Billing App backend Service
abillingapp_back:
   build:
    context: .java # A partir de donde va a leer el archivo
    args: 
     -JAR_FILE=*.jar 
     -DB_PASSWORD=qwerty
    container_name: billingapp-back
    # Variables de entorno
    # (Xms) memoria minima global asignada
    # (Xmx) Memoria maxima global asignada
    environment:
     - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
     -postgres_db
    ports:
     -8080:8080
  #Billing App frontend  Service
   billingapp_front:
     build:
       context: ./angular
     container_name: billingapp_front
     depends_on:
      -abillingapp_back
     ports:
      - 80:80




